// Command fingerprint content-hashes the v3 webapp's top-level built assets
// (app.css, app.js) so production deploys never serve stale CSS/JS. It is the
// top-level analogue of buildjs (which already fingerprints the JS islands).
//
// It runs AFTER the assets are built (`make webapp-css`, the committed app.js):
// for each input it computes a SHA-256, writes a content-hashed sibling copy
// (e.g. static/css/app-<hash>.css) with a lowercase-hex hash that embed.go's
// looksFingerprinted recognizes for immutable long-cache, leaves the unhashed
// original in place (dev fallback + //go:embed all:static still resolve), and
// regenerates internal/webapp/layout/assets_manifest.go: a small Go map from
// logical asset name → public URL. templ/Go resolve the hashed URL via
// layout.AssetURL("app.css"), falling back to the unhashed path when absent.
//
// Node-free, pure Go file ops. Run: go run ./internal/webapp/cmd/fingerprint
// (or `make webapp-assets`).
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// asset describes one top-level asset to fingerprint: its on-disk source path,
// the logical name used as the manifest key, and the public-URL directory it is
// served from.
type asset struct {
	logical string // manifest key, e.g. "app.css"
	src     string // on-disk path of the unhashed built file
	urlDir  string // public URL directory, e.g. "/app/static/css"
}

var assets = []asset{
	{logical: "app.css", src: "internal/webapp/static/css/app.css", urlDir: "/app/static/css"},
	{logical: "app.js", src: "internal/webapp/static/js/app.js", urlDir: "/app/static/js"},
}

const manifestPath = "internal/webapp/layout/assets_manifest.go"

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "fingerprint:", err)
		os.Exit(1)
	}
}

func run() error {
	manifest := make(map[string]string, len(assets))
	for _, a := range assets {
		data, err := os.ReadFile(a.src)
		if err != nil {
			// Asset not built yet — skip it. AssetURL falls back to the
			// unhashed path, so dev/un-fingerprinted builds still render.
			if os.IsNotExist(err) {
				continue
			}
			return err
		}

		dir := filepath.Dir(a.src)
		base := filepath.Base(a.src)         // app.css
		ext := filepath.Ext(base)            // .css
		stem := strings.TrimSuffix(base, ext) // app

		if err := cleanStale(dir, stem, ext); err != nil {
			return err
		}

		sum := sha256.Sum256(data)
		hash := hex.EncodeToString(sum[:])[:8] // lowercase hex; embed.go honors immutable
		hashed := fmt.Sprintf("%s-%s%s", stem, hash, ext)
		if err := os.WriteFile(filepath.Join(dir, hashed), data, 0o644); err != nil {
			return err
		}
		manifest[a.logical] = a.urlDir + "/" + hashed
		fmt.Printf("fingerprint: %s -> %s\n", a.logical, manifest[a.logical])
	}
	return writeManifest(manifest)
}

// cleanStale removes previously generated <stem>-<hash><ext> copies in dir so
// old hashes don't accumulate in the embed. It never touches the unhashed
// original (<stem><ext>).
func cleanStale(dir, stem, ext string) error {
	matches, err := filepath.Glob(filepath.Join(dir, stem+"-*"+ext))
	if err != nil {
		return err
	}
	for _, f := range matches {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	return nil
}

func writeManifest(m map[string]string) error {
	names := make([]string, 0, len(m))
	for k := range m {
		names = append(names, k)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("//go:build !headless && !lite\n\n")
	b.WriteString("// Code generated by internal/webapp/cmd/fingerprint. DO NOT EDIT.\n\n")
	b.WriteString("package layout\n\n")
	b.WriteString("// Assets maps a logical top-level asset name (e.g. \"app.css\") to its\n")
	b.WriteString("// content-hashed public URL under /app/static/. Resolve URLs via AssetURL.\n")
	b.WriteString("var Assets = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %q,\n", name, m[name])
	}
	b.WriteString("}\n")

	return os.WriteFile(manifestPath, []byte(b.String()), 0o644)
}
