//go:build !headless && !lite

// Code generated by internal/webapp/cmd/buildjs. DO NOT EDIT.

package islands

// Manifest maps a logical island name to its content-hashed built filename
// under /app/static/js/islands/. Resolve URLs via layout.IslandSrc.
var Manifest = map[string]string{
	"palette": "palette-SYBGVEW7.js",
}
