#!/usr/bin/env bash
set -euo pipefail

# --- Color helpers ---
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

info()    { echo -e "${BLUE}[INFO]${NC} $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC} $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; }
success() { echo -e "${GREEN}[OK]${NC} $*"; }

# --- Root check ---
if [[ $EUID -ne 0 ]]; then
    error "This script must be run as root or with sudo."
    exit 1
fi

# --- Install directory ---
INSTALL_DIR="${INSTALL_DIR:-/opt/breadbox}"
GITHUB_BASE="https://raw.githubusercontent.com/canalesb93/breadbox/main/deploy"

# --- Check for existing installation ---
if [[ -f "$INSTALL_DIR/.env" ]]; then
    warn "Existing installation detected at $INSTALL_DIR"
    echo ""
    read -rp "Do you want to (U)pdate or (R)e-install? [U/r]: " choice
    choice="${choice:-U}"
    if [[ "${choice,,}" == "u" ]]; then
        info "Pulling latest images..."
        cd "$INSTALL_DIR"
        docker compose -f docker-compose.prod.yml pull
        docker compose -f docker-compose.prod.yml up -d
        info "Waiting for Breadbox to become healthy..."
        for i in $(seq 1 60); do
            if curl -sf http://localhost:8080/health/ready > /dev/null 2>&1; then
                success "Breadbox is healthy!"
                exit 0
            fi
            sleep 1
        done
        error "Breadbox did not become healthy within 60 seconds."
        exit 1
    fi
    info "Re-installing from scratch..."
fi

# --- Check for Docker ---
if ! command -v docker &> /dev/null; then
    warn "Docker is not installed."
    read -rp "Install Docker via get.docker.com? [Y/n]: " install_docker
    install_docker="${install_docker:-Y}"
    if [[ "${install_docker,,}" == "y" ]]; then
        info "Installing Docker..."
        curl -fsSL https://get.docker.com | sh
        systemctl enable --now docker
        success "Docker installed."
    else
        error "Docker is required. Please install it and re-run this script."
        exit 1
    fi
fi

# --- Check for Docker Compose ---
if ! docker compose version &> /dev/null; then
    warn "Docker Compose plugin is not available."
    read -rp "Install Docker (includes Compose) via get.docker.com? [Y/n]: " install_compose
    install_compose="${install_compose:-Y}"
    if [[ "${install_compose,,}" == "y" ]]; then
        info "Installing Docker..."
        curl -fsSL https://get.docker.com | sh
        systemctl enable --now docker
        success "Docker installed with Compose plugin."
    else
        error "Docker Compose is required. Please install it and re-run this script."
        exit 1
    fi
fi

# --- Prompt for configuration ---
echo ""
info "=== Breadbox Setup ==="
echo ""

read -rp "Domain name (e.g. breadbox.example.com): " DOMAIN
if [[ -z "$DOMAIN" ]]; then
    error "Domain name is required."
    exit 1
fi

read -rp "Admin email (for Let's Encrypt): " ADMIN_EMAIL
if [[ -z "$ADMIN_EMAIL" ]]; then
    error "Admin email is required."
    exit 1
fi

# --- Auto-generate secrets ---
info "Generating secrets..."
ENCRYPTION_KEY=$(openssl rand -hex 32)
POSTGRES_PASSWORD=$(openssl rand -base64 32 | tr -d '=/+')

# --- Create install directory ---
info "Setting up $INSTALL_DIR..."
mkdir -p "$INSTALL_DIR"

# --- Download files from GitHub ---
info "Downloading deployment files..."
curl -fsSL "$GITHUB_BASE/docker-compose.prod.yml" -o "$INSTALL_DIR/docker-compose.prod.yml"
curl -fsSL "$GITHUB_BASE/Caddyfile" -o "$INSTALL_DIR/Caddyfile"
curl -fsSL "$GITHUB_BASE/.env.example" -o "$INSTALL_DIR/.env.example"

# --- Write .env file ---
info "Writing configuration..."
cat > "$INSTALL_DIR/.env" <<EOF
# Breadbox Production Configuration
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# --- Domain ---
DOMAIN=${DOMAIN}

# --- Database ---
DATABASE_URL=postgres://breadbox:${POSTGRES_PASSWORD}@db:5432/breadbox?sslmode=disable

# --- Security ---
ENCRYPTION_KEY=${ENCRYPTION_KEY}

# --- Server ---
SERVER_PORT=8080
ENVIRONMENT=docker

# --- Plaid (optional) ---
# PLAID_CLIENT_ID=
# PLAID_SECRET=
# PLAID_ENV=sandbox

# --- Teller (optional) ---
# TELLER_APP_ID=
# TELLER_CERT_PATH=
# TELLER_KEY_PATH=
# TELLER_ENV=sandbox
# TELLER_WEBHOOK_SECRET=

# --- Docker Compose (used by db service) ---
POSTGRES_USER=breadbox
POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
POSTGRES_DB=breadbox
EOF

chmod 600 "$INSTALL_DIR/.env"

# --- Start services ---
info "Starting Breadbox..."
cd "$INSTALL_DIR"
docker compose -f docker-compose.prod.yml up -d

# --- Wait for healthy ---
info "Waiting for Breadbox to become healthy..."
for i in $(seq 1 60); do
    if curl -sf http://localhost:8080/health/ready > /dev/null 2>&1; then
        success "Breadbox is healthy!"
        echo ""
        success "========================================="
        success "  Breadbox is running!"
        success "========================================="
        echo ""
        info "Access your instance at: https://${DOMAIN}"
        info "Create your admin account at: https://${DOMAIN}/admin/setup"
        echo ""
        info "Configuration file: $INSTALL_DIR/.env"
        info "To view logs: cd $INSTALL_DIR && docker compose -f docker-compose.prod.yml logs -f"
        echo ""
        exit 0
    fi
    sleep 1
done

error "Breadbox did not become healthy within 60 seconds."
error "Check logs with: cd $INSTALL_DIR && docker compose -f docker-compose.prod.yml logs"
exit 1
