// Command buildjs bundles the v3 webapp's JS islands with esbuild's Go API —
// no Node, no npm. It is the JS analogue of `make webapp-css` (Tailwind standalone CLI).
//
// Each TypeScript entrypoint under internal/webapp/assets/js/islands/*.ts is bundled,
// minified, and written to internal/webapp/static/js/islands/<name>-<hash>.js with a
// content hash in the filename for immutable caching (the embed.go cache logic already
// special-cases `…-<hash>.js`). Because the hash is unknowable at template-author time,
// we also generate internal/webapp/static/js/islands/manifest.go: a small Go map from
// logical island name → built filename, so templ/Go can resolve the hashed URL via
// layout.IslandSrc("palette").
//
// Run: go run ./internal/webapp/cmd/buildjs  (or `make webapp-js`).
package main

import (
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/evanw/esbuild/pkg/api"
)

const (
	srcDir = "internal/webapp/assets/js/islands"
	outDir = "internal/webapp/static/js/islands"
)

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "buildjs:", err)
		os.Exit(1)
	}
}

func run() error {
	entries, err := filepath.Glob(filepath.Join(srcDir, "*.ts"))
	if err != nil {
		return err
	}
	if len(entries) == 0 {
		// No islands yet — still emit an empty manifest + keep the dir present
		// so //go:embed all:static resolves. (The committed .gitkeep also guards this.)
		return writeManifest(map[string]string{})
	}
	sort.Strings(entries)

	// Clean stale built bundles so old hashes don't accumulate in the embed.
	if err := cleanBuiltJS(); err != nil {
		return err
	}

	result := api.Build(api.BuildOptions{
		EntryPoints:       entries,
		Bundle:            true,
		MinifyWhitespace:  true,
		MinifyIdentifiers: true,
		MinifySyntax:      true,
		Format:            api.FormatESModule,
		Target:            api.ES2022,
		Outdir:            outDir,
		EntryNames:        "[name]-[hash]",
		Write:             true,
		Metafile:          true,
		LogLevel:          api.LogLevelWarning,
		Sourcemap:         api.SourceMapNone,
	})
	if len(result.Errors) > 0 {
		msgs := api.FormatMessages(result.Errors, api.FormatMessagesOptions{Color: false, Kind: api.ErrorMessage})
		return fmt.Errorf("esbuild failed:\n%s", strings.Join(msgs, "\n"))
	}

	manifest, err := manifestFromOutputs(result.OutputFiles)
	if err != nil {
		return err
	}
	if err := writeManifest(manifest); err != nil {
		return err
	}
	for name, file := range manifest {
		fmt.Printf("buildjs: %s -> %s\n", name, file)
	}
	return nil
}

// manifestFromOutputs maps each entrypoint's logical name (e.g. "palette") to the
// hashed output basename (e.g. "palette-XU7K2A9P.js"). The .js.map files (if any) are skipped.
func manifestFromOutputs(outputs []api.OutputFile) (map[string]string, error) {
	m := make(map[string]string, len(outputs))
	for _, o := range outputs {
		base := filepath.Base(o.Path)
		if !strings.HasSuffix(base, ".js") {
			continue
		}
		// base is "<name>-<HASH>.js"; logical name is everything before the last dash.
		stem := strings.TrimSuffix(base, ".js")
		dash := strings.LastIndex(stem, "-")
		if dash < 0 {
			return nil, fmt.Errorf("unexpected output name without hash: %s", base)
		}
		m[stem[:dash]] = base
	}
	return m, nil
}

// cleanBuiltJS removes previously generated *.js bundles in outDir (but never the
// committed .gitkeep or the generated manifest.go, which writeManifest overwrites).
func cleanBuiltJS() error {
	old, err := filepath.Glob(filepath.Join(outDir, "*.js"))
	if err != nil {
		return err
	}
	for _, f := range old {
		if err := os.Remove(f); err != nil {
			return err
		}
	}
	return nil
}

func writeManifest(m map[string]string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return err
	}
	names := make([]string, 0, len(m))
	for k := range m {
		names = append(names, k)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("//go:build !headless && !lite\n\n")
	b.WriteString("// Code generated by internal/webapp/cmd/buildjs. DO NOT EDIT.\n\n")
	b.WriteString("package islands\n\n")
	b.WriteString("// Manifest maps a logical island name to its content-hashed built filename\n")
	b.WriteString("// under /app/static/js/islands/. Resolve URLs via layout.IslandSrc.\n")
	b.WriteString("var Manifest = map[string]string{\n")
	for _, name := range names {
		fmt.Fprintf(&b, "\t%q: %q,\n", name, m[name])
	}
	b.WriteString("}\n")

	return os.WriteFile(filepath.Join(outDir, "manifest.go"), []byte(b.String()), 0o644)
}
