// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: account_links.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const accountLinkExists = `-- name: AccountLinkExists :one
SELECT EXISTS(
    SELECT 1 FROM account_links
    WHERE primary_account_id = $1 AND dependent_account_id = $2
) AS exists
`

type AccountLinkExistsParams struct {
	PrimaryAccountID   pgtype.UUID
	DependentAccountID pgtype.UUID
}

func (q *Queries) AccountLinkExists(ctx context.Context, arg AccountLinkExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, accountLinkExists, arg.PrimaryAccountID, arg.DependentAccountID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createAccountLink = `-- name: CreateAccountLink :one
INSERT INTO account_links (primary_account_id, dependent_account_id, match_strategy, match_tolerance_days)
VALUES ($1, $2, $3, $4)
RETURNING id, primary_account_id, dependent_account_id, match_strategy, match_tolerance_days, enabled, created_at, updated_at, short_id
`

type CreateAccountLinkParams struct {
	PrimaryAccountID   pgtype.UUID
	DependentAccountID pgtype.UUID
	MatchStrategy      string
	MatchToleranceDays int32
}

func (q *Queries) CreateAccountLink(ctx context.Context, arg CreateAccountLinkParams) (AccountLink, error) {
	row := q.db.QueryRow(ctx, createAccountLink,
		arg.PrimaryAccountID,
		arg.DependentAccountID,
		arg.MatchStrategy,
		arg.MatchToleranceDays,
	)
	var i AccountLink
	err := row.Scan(
		&i.ID,
		&i.PrimaryAccountID,
		&i.DependentAccountID,
		&i.MatchStrategy,
		&i.MatchToleranceDays,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortID,
	)
	return i, err
}

const deleteAccountLink = `-- name: DeleteAccountLink :exec
DELETE FROM account_links WHERE id = $1
`

func (q *Queries) DeleteAccountLink(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountLink, id)
	return err
}

const getAccountLink = `-- name: GetAccountLink :one
SELECT al.id, al.primary_account_id, al.dependent_account_id, al.match_strategy, al.match_tolerance_days, al.enabled, al.created_at, al.updated_at, al.short_id,
       pa.name AS primary_account_name,
       COALESCE(pa.display_name, pa.name) AS primary_account_display_name,
       da.name AS dependent_account_name,
       COALESCE(da.display_name, da.name) AS dependent_account_display_name,
       pu.name AS primary_user_name,
       du.name AS dependent_user_name
FROM account_links al
JOIN accounts pa ON al.primary_account_id = pa.id
JOIN accounts da ON al.dependent_account_id = da.id
LEFT JOIN bank_connections pbc ON pa.connection_id = pbc.id
LEFT JOIN users pu ON pbc.user_id = pu.id
LEFT JOIN bank_connections dbc ON da.connection_id = dbc.id
LEFT JOIN users du ON dbc.user_id = du.id
WHERE al.id = $1
`

type GetAccountLinkRow struct {
	ID                          pgtype.UUID
	PrimaryAccountID            pgtype.UUID
	DependentAccountID          pgtype.UUID
	MatchStrategy               string
	MatchToleranceDays          int32
	Enabled                     bool
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	ShortID                     string
	PrimaryAccountName          string
	PrimaryAccountDisplayName   string
	DependentAccountName        string
	DependentAccountDisplayName string
	PrimaryUserName             pgtype.Text
	DependentUserName           pgtype.Text
}

func (q *Queries) GetAccountLink(ctx context.Context, id pgtype.UUID) (GetAccountLinkRow, error) {
	row := q.db.QueryRow(ctx, getAccountLink, id)
	var i GetAccountLinkRow
	err := row.Scan(
		&i.ID,
		&i.PrimaryAccountID,
		&i.DependentAccountID,
		&i.MatchStrategy,
		&i.MatchToleranceDays,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortID,
		&i.PrimaryAccountName,
		&i.PrimaryAccountDisplayName,
		&i.DependentAccountName,
		&i.DependentAccountDisplayName,
		&i.PrimaryUserName,
		&i.DependentUserName,
	)
	return i, err
}

const getAccountLinkUUIDByShortID = `-- name: GetAccountLinkUUIDByShortID :one
SELECT id FROM account_links WHERE short_id = $1
`

func (q *Queries) GetAccountLinkUUIDByShortID(ctx context.Context, shortID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getAccountLinkUUIDByShortID, shortID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getDependentUserID = `-- name: GetDependentUserID :one
SELECT u.id FROM accounts a
JOIN bank_connections bc ON a.connection_id = bc.id
JOIN users u ON bc.user_id = u.id
WHERE a.id = $1
`

func (q *Queries) GetDependentUserID(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getDependentUserID, id)
	err := row.Scan(&id)
	return id, err
}

const listAccountLinks = `-- name: ListAccountLinks :many
SELECT al.id, al.primary_account_id, al.dependent_account_id, al.match_strategy, al.match_tolerance_days, al.enabled, al.created_at, al.updated_at, al.short_id,
       pa.name AS primary_account_name,
       COALESCE(pa.display_name, pa.name) AS primary_account_display_name,
       da.name AS dependent_account_name,
       COALESCE(da.display_name, da.name) AS dependent_account_display_name,
       pu.name AS primary_user_name,
       du.name AS dependent_user_name
FROM account_links al
JOIN accounts pa ON al.primary_account_id = pa.id
JOIN accounts da ON al.dependent_account_id = da.id
LEFT JOIN bank_connections pbc ON pa.connection_id = pbc.id
LEFT JOIN users pu ON pbc.user_id = pu.id
LEFT JOIN bank_connections dbc ON da.connection_id = dbc.id
LEFT JOIN users du ON dbc.user_id = du.id
ORDER BY al.created_at DESC
`

type ListAccountLinksRow struct {
	ID                          pgtype.UUID
	PrimaryAccountID            pgtype.UUID
	DependentAccountID          pgtype.UUID
	MatchStrategy               string
	MatchToleranceDays          int32
	Enabled                     bool
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	ShortID                     string
	PrimaryAccountName          string
	PrimaryAccountDisplayName   string
	DependentAccountName        string
	DependentAccountDisplayName string
	PrimaryUserName             pgtype.Text
	DependentUserName           pgtype.Text
}

func (q *Queries) ListAccountLinks(ctx context.Context) ([]ListAccountLinksRow, error) {
	rows, err := q.db.Query(ctx, listAccountLinks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAccountLinksRow
	for rows.Next() {
		var i ListAccountLinksRow
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryAccountID,
			&i.DependentAccountID,
			&i.MatchStrategy,
			&i.MatchToleranceDays,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortID,
			&i.PrimaryAccountName,
			&i.PrimaryAccountDisplayName,
			&i.DependentAccountName,
			&i.DependentAccountDisplayName,
			&i.PrimaryUserName,
			&i.DependentUserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountLinksByAccountID = `-- name: ListAccountLinksByAccountID :many
SELECT id, primary_account_id, dependent_account_id, match_strategy, match_tolerance_days, enabled, created_at, updated_at, short_id FROM account_links
WHERE (primary_account_id = $1 OR dependent_account_id = $1) AND enabled = TRUE
`

func (q *Queries) ListAccountLinksByAccountID(ctx context.Context, primaryAccountID pgtype.UUID) ([]AccountLink, error) {
	rows, err := q.db.Query(ctx, listAccountLinksByAccountID, primaryAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountLink
	for rows.Next() {
		var i AccountLink
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryAccountID,
			&i.DependentAccountID,
			&i.MatchStrategy,
			&i.MatchToleranceDays,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAccountLinksByConnectionID = `-- name: ListAccountLinksByConnectionID :many
SELECT DISTINCT al.id, al.primary_account_id, al.dependent_account_id, al.match_strategy, al.match_tolerance_days, al.enabled, al.created_at, al.updated_at, al.short_id FROM account_links al
JOIN accounts a ON a.id = al.primary_account_id OR a.id = al.dependent_account_id
WHERE a.connection_id = $1 AND al.enabled = TRUE
`

func (q *Queries) ListAccountLinksByConnectionID(ctx context.Context, connectionID pgtype.UUID) ([]AccountLink, error) {
	rows, err := q.db.Query(ctx, listAccountLinksByConnectionID, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountLink
	for rows.Next() {
		var i AccountLink
		if err := rows.Scan(
			&i.ID,
			&i.PrimaryAccountID,
			&i.DependentAccountID,
			&i.MatchStrategy,
			&i.MatchToleranceDays,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ShortID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAccountDependentLinked = `-- name: UpdateAccountDependentLinked :exec
UPDATE accounts SET is_dependent_linked = $2, updated_at = NOW() WHERE id = $1
`

type UpdateAccountDependentLinkedParams struct {
	ID                pgtype.UUID
	IsDependentLinked bool
}

func (q *Queries) UpdateAccountDependentLinked(ctx context.Context, arg UpdateAccountDependentLinkedParams) error {
	_, err := q.db.Exec(ctx, updateAccountDependentLinked, arg.ID, arg.IsDependentLinked)
	return err
}

const updateAccountLink = `-- name: UpdateAccountLink :one
UPDATE account_links
SET match_strategy = $2,
    match_tolerance_days = $3,
    enabled = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, primary_account_id, dependent_account_id, match_strategy, match_tolerance_days, enabled, created_at, updated_at, short_id
`

type UpdateAccountLinkParams struct {
	ID                 pgtype.UUID
	MatchStrategy      string
	MatchToleranceDays int32
	Enabled            bool
}

func (q *Queries) UpdateAccountLink(ctx context.Context, arg UpdateAccountLinkParams) (AccountLink, error) {
	row := q.db.QueryRow(ctx, updateAccountLink,
		arg.ID,
		arg.MatchStrategy,
		arg.MatchToleranceDays,
		arg.Enabled,
	)
	var i AccountLink
	err := row.Scan(
		&i.ID,
		&i.PrimaryAccountID,
		&i.DependentAccountID,
		&i.MatchStrategy,
		&i.MatchToleranceDays,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ShortID,
	)
	return i, err
}
