// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ConnectionStatus string

const (
	ConnectionStatusActive        ConnectionStatus = "active"
	ConnectionStatusError         ConnectionStatus = "error"
	ConnectionStatusPendingReauth ConnectionStatus = "pending_reauth"
	ConnectionStatusDisconnected  ConnectionStatus = "disconnected"
)

func (e *ConnectionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ConnectionStatus(s)
	case string:
		*e = ConnectionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ConnectionStatus: %T", src)
	}
	return nil
}

type NullConnectionStatus struct {
	ConnectionStatus ConnectionStatus
	Valid            bool // Valid is true if ConnectionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullConnectionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ConnectionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ConnectionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullConnectionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ConnectionStatus), nil
}

type ProviderType string

const (
	ProviderTypePlaid  ProviderType = "plaid"
	ProviderTypeTeller ProviderType = "teller"
	ProviderTypeCsv    ProviderType = "csv"
)

func (e *ProviderType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProviderType(s)
	case string:
		*e = ProviderType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProviderType: %T", src)
	}
	return nil
}

type NullProviderType struct {
	ProviderType ProviderType
	Valid        bool // Valid is true if ProviderType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProviderType) Scan(value interface{}) error {
	if value == nil {
		ns.ProviderType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProviderType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProviderType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProviderType), nil
}

type SyncStatus string

const (
	SyncStatusInProgress SyncStatus = "in_progress"
	SyncStatusSuccess    SyncStatus = "success"
	SyncStatusError      SyncStatus = "error"
)

func (e *SyncStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncStatus(s)
	case string:
		*e = SyncStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncStatus: %T", src)
	}
	return nil
}

type NullSyncStatus struct {
	SyncStatus SyncStatus
	Valid      bool // Valid is true if SyncStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SyncStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncStatus), nil
}

type SyncTrigger string

const (
	SyncTriggerCron    SyncTrigger = "cron"
	SyncTriggerWebhook SyncTrigger = "webhook"
	SyncTriggerManual  SyncTrigger = "manual"
	SyncTriggerInitial SyncTrigger = "initial"
)

func (e *SyncTrigger) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SyncTrigger(s)
	case string:
		*e = SyncTrigger(s)
	default:
		return fmt.Errorf("unsupported scan type for SyncTrigger: %T", src)
	}
	return nil
}

type NullSyncTrigger struct {
	SyncTrigger SyncTrigger
	Valid       bool // Valid is true if SyncTrigger is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSyncTrigger) Scan(value interface{}) error {
	if value == nil {
		ns.SyncTrigger, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SyncTrigger.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSyncTrigger) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SyncTrigger), nil
}

type Account struct {
	ID                pgtype.UUID
	ConnectionID      pgtype.UUID
	ExternalAccountID string
	Name              string
	OfficialName      pgtype.Text
	Type              string
	Subtype           pgtype.Text
	Mask              pgtype.Text
	BalanceCurrent    pgtype.Numeric
	BalanceAvailable  pgtype.Numeric
	BalanceLimit      pgtype.Numeric
	IsoCurrencyCode   pgtype.Text
	LastBalanceUpdate pgtype.Timestamptz
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
	DisplayName       pgtype.Text
	Excluded          bool
	IsDependentLinked bool
}

type AccountLink struct {
	ID                 pgtype.UUID
	PrimaryAccountID   pgtype.UUID
	DependentAccountID pgtype.UUID
	MatchStrategy      string
	MatchToleranceDays int32
	Enabled            bool
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type AdminAccount struct {
	ID             pgtype.UUID
	Username       string
	HashedPassword []byte
	CreatedAt      pgtype.Timestamptz
}

type ApiKey struct {
	ID         pgtype.UUID
	Name       string
	KeyHash    string
	KeyPrefix  string
	LastUsedAt pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
	Scope      string
}

type AppConfig struct {
	Key       string
	Value     pgtype.Text
	UpdatedAt pgtype.Timestamptz
}

type BankConnection struct {
	ID                          pgtype.UUID
	UserID                      pgtype.UUID
	Provider                    ProviderType
	InstitutionID               pgtype.Text
	InstitutionName             pgtype.Text
	SyncCursor                  pgtype.Text
	Status                      ConnectionStatus
	ErrorCode                   pgtype.Text
	ErrorMessage                pgtype.Text
	NewAccountsAvailable        bool
	ConsentExpirationTime       pgtype.Timestamptz
	LastSyncedAt                pgtype.Timestamptz
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	ExternalID                  pgtype.Text
	EncryptedCredentials        []byte
	Paused                      bool
	SyncIntervalOverrideMinutes pgtype.Int4
}

type Category struct {
	ID          pgtype.UUID
	Slug        string
	DisplayName string
	ParentID    pgtype.UUID
	Icon        pgtype.Text
	Color       pgtype.Text
	SortOrder   int32
	IsSystem    bool
	Hidden      bool
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

type CategoryMapping struct {
	ID               pgtype.UUID
	Provider         ProviderType
	ProviderCategory string
	CategoryID       pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
}

type OauthAccessToken struct {
	ID         pgtype.UUID
	TokenHash  string
	ClientID   string
	AdminID    pgtype.UUID
	Scope      string
	LastUsedAt pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	RevokedAt  pgtype.Timestamptz
	CreatedAt  pgtype.Timestamptz
}

type OauthAuthorizationCode struct {
	CodeHash            string
	ClientID            string
	AdminID             pgtype.UUID
	RedirectUri         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
	UsedAt              pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
}

type OauthClient struct {
	ID               pgtype.UUID
	Name             string
	ClientID         string
	ClientSecretHash string
	ClientIDPrefix   string
	RedirectUris     []string
	Scope            string
	RevokedAt        pgtype.Timestamptz
	CreatedAt        pgtype.Timestamptz
}

type OauthRefreshToken struct {
	ID            pgtype.UUID
	TokenHash     string
	AccessTokenID pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
	RevokedAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
}

type ReviewQueue struct {
	ID                  pgtype.UUID
	TransactionID       pgtype.UUID
	ReviewType          string
	Status              string
	SuggestedCategoryID pgtype.UUID
	ConfidenceScore     pgtype.Numeric
	ReviewerType        pgtype.Text
	ReviewerID          pgtype.Text
	ReviewerName        pgtype.Text
	ReviewNote          pgtype.Text
	ResolvedCategoryID  pgtype.UUID
	CreatedAt           pgtype.Timestamptz
	ReviewedAt          pgtype.Timestamptz
}

type Session struct {
	Token  string
	Data   []byte
	Expiry pgtype.Timestamptz
}

type SyncLog struct {
	ID            pgtype.UUID
	ConnectionID  pgtype.UUID
	Trigger       SyncTrigger
	AddedCount    int32
	ModifiedCount int32
	RemovedCount  int32
	Status        SyncStatus
	ErrorMessage  pgtype.Text
	StartedAt     pgtype.Timestamptz
	CompletedAt   pgtype.Timestamptz
}

type Transaction struct {
	ID                     pgtype.UUID
	AccountID              pgtype.UUID
	ExternalTransactionID  string
	PendingTransactionID   pgtype.Text
	Amount                 pgtype.Numeric
	IsoCurrencyCode        pgtype.Text
	UnofficialCurrencyCode pgtype.Text
	Date                   pgtype.Date
	AuthorizedDate         pgtype.Date
	Datetime               pgtype.Timestamptz
	AuthorizedDatetime     pgtype.Timestamptz
	Name                   string
	MerchantName           pgtype.Text
	CategoryPrimary        pgtype.Text
	CategoryDetailed       pgtype.Text
	CategoryConfidence     pgtype.Text
	PaymentChannel         pgtype.Text
	Pending                bool
	DeletedAt              pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	CategoryID             pgtype.UUID
	CategoryOverride       bool
	AttributedUserID       pgtype.UUID
}

type TransactionComment struct {
	ID            pgtype.UUID
	TransactionID pgtype.UUID
	AuthorType    string
	AuthorID      pgtype.Text
	AuthorName    string
	Content       string
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type TransactionMatch struct {
	ID                     pgtype.UUID
	AccountLinkID          pgtype.UUID
	PrimaryTransactionID   pgtype.UUID
	DependentTransactionID pgtype.UUID
	MatchConfidence        string
	MatchedOn              []string
	CreatedAt              pgtype.Timestamptz
}

type TransactionRule struct {
	ID            pgtype.UUID
	Name          string
	Conditions    []byte
	CategoryID    pgtype.UUID
	Priority      int32
	Enabled       bool
	ExpiresAt     pgtype.Timestamptz
	CreatedByType string
	CreatedByID   pgtype.Text
	CreatedByName string
	HitCount      int32
	LastHitAt     pgtype.Timestamptz
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type User struct {
	ID        pgtype.UUID
	Name      string
	Email     pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}
