// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: oauth.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOAuthAccessToken = `-- name: CreateOAuthAccessToken :one
INSERT INTO oauth_access_tokens (token_hash, client_id, admin_id, scope, expires_at)
VALUES ($1, $2, $3, $4, $5) RETURNING id, token_hash, client_id, admin_id, scope, last_used_at, expires_at, revoked_at, created_at
`

type CreateOAuthAccessTokenParams struct {
	TokenHash string
	ClientID  string
	AdminID   pgtype.UUID
	Scope     string
	ExpiresAt pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAccessToken(ctx context.Context, arg CreateOAuthAccessTokenParams) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, createOAuthAccessToken,
		arg.TokenHash,
		arg.ClientID,
		arg.AdminID,
		arg.Scope,
		arg.ExpiresAt,
	)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.AdminID,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthAuthorizationCode = `-- name: CreateOAuthAuthorizationCode :exec
INSERT INTO oauth_authorization_codes (code_hash, client_id, admin_id, redirect_uri, scope, code_challenge, code_challenge_method, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateOAuthAuthorizationCodeParams struct {
	CodeHash            string
	ClientID            string
	AdminID             pgtype.UUID
	RedirectUri         string
	Scope               string
	CodeChallenge       string
	CodeChallengeMethod string
	ExpiresAt           pgtype.Timestamptz
}

func (q *Queries) CreateOAuthAuthorizationCode(ctx context.Context, arg CreateOAuthAuthorizationCodeParams) error {
	_, err := q.db.Exec(ctx, createOAuthAuthorizationCode,
		arg.CodeHash,
		arg.ClientID,
		arg.AdminID,
		arg.RedirectUri,
		arg.Scope,
		arg.CodeChallenge,
		arg.CodeChallengeMethod,
		arg.ExpiresAt,
	)
	return err
}

const createOAuthClient = `-- name: CreateOAuthClient :one
INSERT INTO oauth_clients (name, client_id, client_secret_hash, client_id_prefix, redirect_uris, scope)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, client_id, client_secret_hash, client_id_prefix, redirect_uris, scope, revoked_at, created_at
`

type CreateOAuthClientParams struct {
	Name             string
	ClientID         string
	ClientSecretHash string
	ClientIDPrefix   string
	RedirectUris     []string
	Scope            string
}

func (q *Queries) CreateOAuthClient(ctx context.Context, arg CreateOAuthClientParams) (OauthClient, error) {
	row := q.db.QueryRow(ctx, createOAuthClient,
		arg.Name,
		arg.ClientID,
		arg.ClientSecretHash,
		arg.ClientIDPrefix,
		arg.RedirectUris,
		arg.Scope,
	)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientIDPrefix,
		&i.RedirectUris,
		&i.Scope,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const createOAuthRefreshToken = `-- name: CreateOAuthRefreshToken :one
INSERT INTO oauth_refresh_tokens (token_hash, access_token_id, expires_at)
VALUES ($1, $2, $3) RETURNING id, token_hash, access_token_id, expires_at, revoked_at, created_at
`

type CreateOAuthRefreshTokenParams struct {
	TokenHash     string
	AccessTokenID pgtype.UUID
	ExpiresAt     pgtype.Timestamptz
}

func (q *Queries) CreateOAuthRefreshToken(ctx context.Context, arg CreateOAuthRefreshTokenParams) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, createOAuthRefreshToken, arg.TokenHash, arg.AccessTokenID, arg.ExpiresAt)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AccessTokenID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpiredOAuthAuthorizationCodes = `-- name: DeleteExpiredOAuthAuthorizationCodes :exec
DELETE FROM oauth_authorization_codes WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOAuthAuthorizationCodes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOAuthAuthorizationCodes)
	return err
}

const getOAuthAccessTokenByHash = `-- name: GetOAuthAccessTokenByHash :one
SELECT id, token_hash, client_id, admin_id, scope, last_used_at, expires_at, revoked_at, created_at FROM oauth_access_tokens WHERE token_hash = $1
`

func (q *Queries) GetOAuthAccessTokenByHash(ctx context.Context, tokenHash string) (OauthAccessToken, error) {
	row := q.db.QueryRow(ctx, getOAuthAccessTokenByHash, tokenHash)
	var i OauthAccessToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ClientID,
		&i.AdminID,
		&i.Scope,
		&i.LastUsedAt,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthAuthorizationCode = `-- name: GetOAuthAuthorizationCode :one
SELECT code_hash, client_id, admin_id, redirect_uri, scope, code_challenge, code_challenge_method, expires_at, used_at, created_at FROM oauth_authorization_codes WHERE code_hash = $1
`

func (q *Queries) GetOAuthAuthorizationCode(ctx context.Context, codeHash string) (OauthAuthorizationCode, error) {
	row := q.db.QueryRow(ctx, getOAuthAuthorizationCode, codeHash)
	var i OauthAuthorizationCode
	err := row.Scan(
		&i.CodeHash,
		&i.ClientID,
		&i.AdminID,
		&i.RedirectUri,
		&i.Scope,
		&i.CodeChallenge,
		&i.CodeChallengeMethod,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthClientByClientID = `-- name: GetOAuthClientByClientID :one
SELECT id, name, client_id, client_secret_hash, client_id_prefix, redirect_uris, scope, revoked_at, created_at FROM oauth_clients WHERE client_id = $1
`

func (q *Queries) GetOAuthClientByClientID(ctx context.Context, clientID string) (OauthClient, error) {
	row := q.db.QueryRow(ctx, getOAuthClientByClientID, clientID)
	var i OauthClient
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ClientID,
		&i.ClientSecretHash,
		&i.ClientIDPrefix,
		&i.RedirectUris,
		&i.Scope,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getOAuthRefreshTokenByHash = `-- name: GetOAuthRefreshTokenByHash :one
SELECT id, token_hash, access_token_id, expires_at, revoked_at, created_at FROM oauth_refresh_tokens WHERE token_hash = $1
`

func (q *Queries) GetOAuthRefreshTokenByHash(ctx context.Context, tokenHash string) (OauthRefreshToken, error) {
	row := q.db.QueryRow(ctx, getOAuthRefreshTokenByHash, tokenHash)
	var i OauthRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.AccessTokenID,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOAuthClients = `-- name: ListOAuthClients :many
SELECT id, name, client_id, client_secret_hash, client_id_prefix, redirect_uris, scope, revoked_at, created_at FROM oauth_clients ORDER BY created_at DESC
`

func (q *Queries) ListOAuthClients(ctx context.Context) ([]OauthClient, error) {
	rows, err := q.db.Query(ctx, listOAuthClients)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OauthClient
	for rows.Next() {
		var i OauthClient
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ClientID,
			&i.ClientSecretHash,
			&i.ClientIDPrefix,
			&i.RedirectUris,
			&i.Scope,
			&i.RevokedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markOAuthAuthorizationCodeUsed = `-- name: MarkOAuthAuthorizationCodeUsed :exec
UPDATE oauth_authorization_codes SET used_at = NOW() WHERE code_hash = $1
`

func (q *Queries) MarkOAuthAuthorizationCodeUsed(ctx context.Context, codeHash string) error {
	_, err := q.db.Exec(ctx, markOAuthAuthorizationCodeUsed, codeHash)
	return err
}

const revokeOAuthAccessTokensByClient = `-- name: RevokeOAuthAccessTokensByClient :exec
UPDATE oauth_access_tokens SET revoked_at = NOW() WHERE client_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthAccessTokensByClient(ctx context.Context, clientID string) error {
	_, err := q.db.Exec(ctx, revokeOAuthAccessTokensByClient, clientID)
	return err
}

const revokeOAuthClient = `-- name: RevokeOAuthClient :exec
UPDATE oauth_clients SET revoked_at = NOW() WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthClient(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthClient, id)
	return err
}

const revokeOAuthRefreshToken = `-- name: RevokeOAuthRefreshToken :exec
UPDATE oauth_refresh_tokens SET revoked_at = NOW() WHERE id = $1
`

func (q *Queries) RevokeOAuthRefreshToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthRefreshToken, id)
	return err
}

const revokeOAuthRefreshTokensByAccessToken = `-- name: RevokeOAuthRefreshTokensByAccessToken :exec
UPDATE oauth_refresh_tokens SET revoked_at = NOW() WHERE access_token_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeOAuthRefreshTokensByAccessToken(ctx context.Context, accessTokenID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeOAuthRefreshTokensByAccessToken, accessTokenID)
	return err
}

const updateOAuthAccessTokenLastUsed = `-- name: UpdateOAuthAccessTokenLastUsed :exec
UPDATE oauth_access_tokens SET last_used_at = NOW() WHERE id = $1
`

func (q *Queries) UpdateOAuthAccessTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateOAuthAccessTokenLastUsed, id)
	return err
}
