// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingReviews = `-- name: CountPendingReviews :one
SELECT COUNT(*) FROM review_queue rq
JOIN transactions t ON rq.transaction_id = t.id
JOIN accounts a ON t.account_id = a.id
WHERE rq.status = 'pending'
  AND t.deleted_at IS NULL
  AND (a.is_dependent_linked = FALSE
       OR NOT EXISTS (SELECT 1 FROM transaction_matches tm WHERE tm.dependent_transaction_id = t.id))
`

func (q *Queries) CountPendingReviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingReviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countReviewsByStatusToday = `-- name: CountReviewsByStatusToday :many
SELECT status, COUNT(*) as count
FROM review_queue
WHERE reviewed_at >= CURRENT_DATE
GROUP BY status
`

type CountReviewsByStatusTodayRow struct {
	Status string
	Count  int64
}

func (q *Queries) CountReviewsByStatusToday(ctx context.Context) ([]CountReviewsByStatusTodayRow, error) {
	rows, err := q.db.Query(ctx, countReviewsByStatusToday)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountReviewsByStatusTodayRow
	for rows.Next() {
		var i CountReviewsByStatusTodayRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteAllPendingReviews = `-- name: DeleteAllPendingReviews :execrows
DELETE FROM review_queue WHERE status = 'pending'
`

func (q *Queries) DeleteAllPendingReviews(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAllPendingReviews)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteReview = `-- name: DeleteReview :exec
DELETE FROM review_queue WHERE id = $1 AND status = 'pending'
`

func (q *Queries) DeleteReview(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteReview, id)
	return err
}

const enqueueReview = `-- name: EnqueueReview :one
INSERT INTO review_queue (transaction_id, review_type, suggested_category_id, confidence_score)
VALUES ($1, $2, $3, $4)
ON CONFLICT (transaction_id) WHERE status = 'pending' DO NOTHING
RETURNING id, transaction_id, review_type, status, suggested_category_id, confidence_score, reviewer_type, reviewer_id, reviewer_name, review_note, resolved_category_id, created_at, reviewed_at
`

type EnqueueReviewParams struct {
	TransactionID       pgtype.UUID
	ReviewType          string
	SuggestedCategoryID pgtype.UUID
	ConfidenceScore     pgtype.Numeric
}

func (q *Queries) EnqueueReview(ctx context.Context, arg EnqueueReviewParams) (ReviewQueue, error) {
	row := q.db.QueryRow(ctx, enqueueReview,
		arg.TransactionID,
		arg.ReviewType,
		arg.SuggestedCategoryID,
		arg.ConfidenceScore,
	)
	var i ReviewQueue
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReviewType,
		&i.Status,
		&i.SuggestedCategoryID,
		&i.ConfidenceScore,
		&i.ReviewerType,
		&i.ReviewerID,
		&i.ReviewerName,
		&i.ReviewNote,
		&i.ResolvedCategoryID,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getPendingReviewByTransactionID = `-- name: GetPendingReviewByTransactionID :one
SELECT id, transaction_id, review_type, status, suggested_category_id, confidence_score, reviewer_type, reviewer_id, reviewer_name, review_note, resolved_category_id, created_at, reviewed_at FROM review_queue WHERE transaction_id = $1 AND status = 'pending'
`

func (q *Queries) GetPendingReviewByTransactionID(ctx context.Context, transactionID pgtype.UUID) (ReviewQueue, error) {
	row := q.db.QueryRow(ctx, getPendingReviewByTransactionID, transactionID)
	var i ReviewQueue
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReviewType,
		&i.Status,
		&i.SuggestedCategoryID,
		&i.ConfidenceScore,
		&i.ReviewerType,
		&i.ReviewerID,
		&i.ReviewerName,
		&i.ReviewNote,
		&i.ResolvedCategoryID,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const getReviewByID = `-- name: GetReviewByID :one
SELECT id, transaction_id, review_type, status, suggested_category_id, confidence_score, reviewer_type, reviewer_id, reviewer_name, review_note, resolved_category_id, created_at, reviewed_at FROM review_queue WHERE id = $1
`

func (q *Queries) GetReviewByID(ctx context.Context, id pgtype.UUID) (ReviewQueue, error) {
	row := q.db.QueryRow(ctx, getReviewByID, id)
	var i ReviewQueue
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReviewType,
		&i.Status,
		&i.SuggestedCategoryID,
		&i.ConfidenceScore,
		&i.ReviewerType,
		&i.ReviewerID,
		&i.ReviewerName,
		&i.ReviewNote,
		&i.ResolvedCategoryID,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}

const updateReviewDecision = `-- name: UpdateReviewDecision :one
UPDATE review_queue
SET status = $2,
    reviewer_type = $3,
    reviewer_id = $4,
    reviewer_name = $5,
    review_note = $6,
    resolved_category_id = $7,
    reviewed_at = NOW()
WHERE id = $1 AND status = 'pending'
RETURNING id, transaction_id, review_type, status, suggested_category_id, confidence_score, reviewer_type, reviewer_id, reviewer_name, review_note, resolved_category_id, created_at, reviewed_at
`

type UpdateReviewDecisionParams struct {
	ID                 pgtype.UUID
	Status             string
	ReviewerType       pgtype.Text
	ReviewerID         pgtype.Text
	ReviewerName       pgtype.Text
	ReviewNote         pgtype.Text
	ResolvedCategoryID pgtype.UUID
}

func (q *Queries) UpdateReviewDecision(ctx context.Context, arg UpdateReviewDecisionParams) (ReviewQueue, error) {
	row := q.db.QueryRow(ctx, updateReviewDecision,
		arg.ID,
		arg.Status,
		arg.ReviewerType,
		arg.ReviewerID,
		arg.ReviewerName,
		arg.ReviewNote,
		arg.ResolvedCategoryID,
	)
	var i ReviewQueue
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.ReviewType,
		&i.Status,
		&i.SuggestedCategoryID,
		&i.ConfidenceScore,
		&i.ReviewerType,
		&i.ReviewerID,
		&i.ReviewerName,
		&i.ReviewNote,
		&i.ResolvedCategoryID,
		&i.CreatedAt,
		&i.ReviewedAt,
	)
	return i, err
}
